services:
  api:
    container_name: chat-ai
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '2121:2121'
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - shared-network

networks:
  shared-network:
    external: true
    name: shared-network-production
